DROP TABLE IF EXISTS `OBRAS`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `OBRAS` (
  `ID_OBRA` int(11) NOT NULL AUTO_INCREMENT,
  `NOM_OBRA` varchar(255) DEFAULT NULL,
  `DES_OBRA` varchar(2000) DEFAULT NULL,
  `NOM_AUTOR` varchar(255) DEFAULT NULL,
  `NOM_EDITORA` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID_OBRA`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS `LIVROS`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `LIVROS` (
  `ID_LIVRO` int(11) NOT NULL AUTO_INCREMENT,
  `COD_OBRA` int(11) DEFAULT NULL,
  `STT_LIVRO` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID_LIVRO`),
  KEY `fk_LIVROS_OBRA_idx` (`COD_OBRA`),
  CONSTRAINT `fk_LIVROS_OBRA` FOREIGN KEY (`COD_OBRA`) REFERENCES `OBRAS` (`ID_OBRA`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS `PESSOAS`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `PESSOAS` (
  `ID_PESSOA` int(11) NOT NULL AUTO_INCREMENT,
  `NOM_PESSOA` varchar(255) DEFAULT NULL,
  `TEL_PESSOA` varchar(20) DEFAULT NULL,
  `COD_PESSOA_TELEGRAM` int(11) DEFAULT NULL,
  `USR_PESSOA` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID_PESSOA`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS `EMPRESTIMOS`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `EMPRESTIMOS` (
  `ID_EMPRESTIMO` int(11) NOT NULL AUTO_INCREMENT,
  `COD_LIVRO` int(11) NOT NULL,
  `COD_PESSOA` int(11) NOT NULL,
  `DATA_EMPRESTIMO` datetime NOT NULL,
  `NUM_EMPRESTIMO` int(11) DEFAULT NULL,
  `SIT_EMPRESTIMO` varchar(45) DEFAULT NULL,
  `DATA_DEVOLUCAO` datetime DEFAULT NULL,
  PRIMARY KEY (`ID_EMPRESTIMO`),
  KEY `fk_EMPRESTIMOS_LIVROS_idx` (`COD_LIVRO`),
  KEY `fk_EMPRESTIMOS_PESSOAS_idx` (`COD_PESSOA`),
  CONSTRAINT `fk_EMPRESTIMOS_LIVROS` FOREIGN KEY (`COD_LIVRO`) REFERENCES `LIVROS` (`ID_LIVRO`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_EMPRESTIMOS_PESSOAS` FOREIGN KEY (`COD_PESSOA`) REFERENCES `PESSOAS` (`ID_PESSOA`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=latin1;



DROP TABLE IF EXISTS `COMENTARIOS`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `COMENTARIOS` (
  `ID_COMENTARIOS` int(11) NOT NULL AUTO_INCREMENT,
  `COD_LIVRO` int(11) DEFAULT NULL,
  `COD_PESSOA` int(11) DEFAULT NULL,
  `COMENTARIO` varchar(2000) DEFAULT NULL,
  `DATA_CADASTRAMENTO` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DATA_FIM` datetime DEFAULT NULL,
  PRIMARY KEY (`ID_COMENTARIOS`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;