select ID_OBRA, NOM_OBRA  
 From LIVROS LIV
 INNER JOIN OBRA OBR ON OBR.ID_OBRA = LIV.COD_OBRA 
 left join EMPRESTIMOS EMP ON EMP.COD_LIVRO = LIV.ID_LIVRO AND DATA_DEVOLUCAO IS NULL
where ID_EMPRESTIMO IS NULL 
GROUP BY ID_OBRA, NOM_OBRA
 order by NOM_OBRA 