SELECT OBRA.ID_OBRA, OBRA.NOM_OBRA, COUNT(OBRA.ID_OBRA)
FROM EMPRESTIMOS
LEFT JOIN LIVROS ON LIVROS.ID_LIVRO = EMPRESTIMOS.COD_LIVRO 
LEFT JOIN OBRA ON LIVROS.COD_OBRA = OBRA.ID_OBRA
LEFT JOIN PESSOAS ON PESSOAS.ID_PESSOA = EMPRESTIMOS.COD_PESSOA
WHERE EMPRESTIMOS.DATA_DEVOLUCAO IS NULL
AND PESSOAS.COD_PESSOA_TELEGRAM = @CPT
GROUP BY OBRA.ID_OBRA, OBRA.NOM_OBRA


select * from EMPRESTIMOS